apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ft9lgn1mt-java-quarkus
  janus-idp.io/tekton: ft9lgn1mt-java-quarkus
  backstage.io/kubernetes-id: ft9lgn1mt-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ft9lgn1mt-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
