apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ft9lgn1mt-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-936a86f36a.nhyx.p3.openshiftapps.com/rhtap/rhtap-qe:3fb192967182a5e7e6a6956b60cc2ebc186d0dd3@sha256:94089c91477ea63bf46ae1c9e882eda7efa2c6125e880f79f9b6276c66ac31a8
          name: container-image
